# Exercices for Numpy

1- Import numpy as `np` and print the version number. 

In [7]:
# Your code here
import numpy as np
np.__version__

'1.19.5'

2- Create a 1D array of numbers from 0 to 9 
- Desired output:
```Python
#> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [7]:
# Your code here
np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3- Create a 3×3 numpy array of all True’s
- Desired output:
```Python
#> array([[ True,  True,  True],
#>        [ True,  True,  True],
#>        [ True,  True,  True]], dtype=bool)
```

In [8]:
# Your code here
c = np.full((3,3), True) # Create a constant array
c

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

4- Extract all odd numbers from `arr` 
- Input:
```Python
#> arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```
- Desired output:
```Python
#> array([1, 3, 5, 7, 9])
```

In [181]:
# Your code here
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
res=np.array([],dtype=int)
for i in arr:
    if i%2!=0:
        res=np.append(res,i)
res

array([1, 3, 5, 7, 9])

In [182]:
#other method using mask 

mask = (arr%2!=0)
arr=arr[mask]
arr

array([1, 3, 5, 7, 9])

5- Replace all odd numbers in arr with -1
- Input:
```Python
#> arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```
- Desired output:
```Python
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
```

In [33]:
# Your code here
arr = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9]) 
 
odd_values = (arr%2 !=0) 

print(odd_values)
arr[odd_values] = -1 
arr

[ True False  True False  True False  True False  True]


array([-1,  2, -1,  4, -1,  6, -1,  8, -1])

6- Replace all odd numbers in arr with -1 without changing `arr` 
- Input:
```Python
#> arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```
- Desired output:
```Python
out
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
arr
#>  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [38]:
# Your code here
arr = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9]) 
res=arr.copy()
odd_values = (arr%2 !=0) 

res[odd_values] = -1 
res

array([-1,  2, -1,  4, -1,  6, -1,  8, -1])

7- Convert a 1D array to a 2D array with 2 rows
- Input:
```Python
#> arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```
- Desired output:
```Python
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])
```

In [183]:
# Your code here

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

8- Stack arrays `a` and `b` vertically 
- Input
```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```
- Desired output:
```Python
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])
```

In [91]:
# Your code here
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
a.shape[0]

c=np.zeros((a.shape[0]+b.shape[0],a.shape[1]),dtype=int)
c[:a.shape[0],:a.shape[1]]=a
c[a.shape[0]:a.shape[0]+b.shape[0],0:b.shape[1]]=b
#we can use  also:
d=np.vstack((a,b))
print(c)
print(d)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


9- Stack the arrays a and b horizontally.
- Input
```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```
- Desired output:
```Python
#> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#>        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
```

In [92]:
# Your code here
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
c=np.zeros((a.shape[0],a.shape[1]+b.shape[1]),dtype=int)
c[:a.shape[0],:a.shape[1]]=a

c[0:a.shape[0],a.shape[1]:a.shape[1]+b.shape[1]]=b
c

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

10- Get the common items between `a` and `b` 
- Input
```Python
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
```
- Desired output:
```Python
#> array([2, 4])
```

In [103]:
# Your code here
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
res=np.array([], dtype=int)
for i in a:
    for j in b:
        if i==j:
            res=np.append(res,i)
            #we add break to avoid repetution for example if b=[5,6,7,8,5]
            #so if we don't add break we will get two 5 as result 
            break 
res       

array([5])

11- From array `a` remove all items present in array `b` 
- Input
```Python
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
```
- Desired output:
```Python
#> array([1,2,3,4])
```

In [124]:
# Your code here
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

for count_A ,value_A in enumerate(a):
    for count_B,value_B in enumerate(b):
        if value_A==value_B:
            a=np.delete(a, count_A)
a

array([1, 2, 3, 4])

12- Get the positions where elements of `a` and `b` match
- Input
```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```
- Desired output:
```Python
#> (array([1, 3, 5, 7]),)
```

In [125]:
# Your code here
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
res=np.array([],dtype=int)
for i in range(len(a)):
    if a[i]==b[i]:
        res=np.append(res,i)
res

array([1, 3, 5, 7])

13- Get all items between 5 and 10 from `a`
- Input
```Python
a = np.array([2, 6, 1, 9, 10, 3, 27])
```
- Desired output:
```Python
#> (array([6, 9, 10]),)
```

In [187]:
# Your code here

a = np.array([2, 6, 1, 9, 10, 3, 27])
mask = (a >= 5)
a=a[mask]
a

array([ 6,  9, 10, 27])

14- Convert the function `maxx` that works on two scalars, to work on two arrays
- Input
```Python
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
```
```Python
maxx(1, 5)
#> 5
```

- Desired output:

```Python
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])
```

In [194]:
# Your code here
def maxx(x, y):
    if x >= y:
        return x
    else:
        return y
def pair_max(a,b):
    res= np.array([])
    for i in range(len(a)):
        
        res=np.append(res,maxx(a[i],b[i]))
    return res
        
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a,b)
    


array([6., 7., 9., 8., 9., 7., 5.])

15- Reverse the rows of a 2D array `arr`
- Input
```Python
arr = np.arange(9).reshape(3,3)
```
- Desired output:
```Python
#> array([[6, 7, 8],
#>       [3, 4, 5],
#>       [0, 1, 2]])
```

In [269]:
# Your code here
arr = np.arange(9).reshape(3,3)
n_row=arr.shape[0]
n_col=arr.shape[1]
res=np.zeros((n_row,n_col))

for i in range(n_row):
    res[n_row-i-1:n_row-i,0:n_col]=arr[i:i+1,0:n_col]
    
print(res)
#other method
print(arr[::-1])

[[6. 7. 8.]
 [3. 4. 5.]
 [0. 1. 2.]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]


16- Reverse the columns of a 2D array `arr`
- Input
```Python
arr = np.arange(9).reshape(3,3)
```
- Desired output:
```Python
#> array([[6, 7, 8],
#>       [3, 4, 5],
#>       [0, 1, 2]]
```

In [271]:
# Your code here
arr = np.arange(9).reshape(3,3)
n_row=arr.shape[0]
n_col=arr.shape[1]
res=np.zeros((n_row,n_col))

for i in range(n_col):
    res[0:n_row,n_col-i-1:n_col-i]=arr[0:n_row,i:i+1]

    
print(res)
#other method 
print(arr[:, ::-1])

[[2. 1. 0.]
 [5. 4. 3.]
 [8. 7. 6.]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]


17- Create a 2D array of shape 5×3 to contain random decimal numbers between 5 and 10 (use `np.random.seed()` to generate the same random output).
- Desired output: (for seed number equal 10)
```Python
#> array([[6.15037787, 9.68381843, 5.81660184],
#>       [6.33607158, 8.89081653, 9.19812181],
#>       [6.03061665, 5.87761494, 6.72743551],
#>       [7.54088093, 5.13145815, 6.41366737],
#>       [5.77872881, 7.58390137, 5.18263144]])
```

In [246]:
import random
import decimal
np.random.seed(0)
arr = np.zeros((5,3))
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        arr[i,j] = np.random.uniform(5, 10)
arr

array([[7.74406752, 8.57594683, 8.01381688],
       [7.72441591, 7.118274  , 8.22947057],
       [7.18793606, 9.458865  , 9.8183138 ],
       [6.91720759, 8.95862519, 7.6444746 ],
       [7.84022281, 9.62798319, 5.35518029]])

18- Print or show only 3 decimal places of the numpy array `rand_arr`
- Input
```Python
rand_arr = np.random.random((5,3))
```
- Desired output:
```Python
rand_arr[:4]
#> array([[ 0.443,  0.109,  0.97 ],
#>        [ 0.388,  0.447,  0.191],
#>        [ 0.891,  0.474,  0.212],
#>        [ 0.609,  0.518,  0.403]])
```

In [254]:
# Your code here
rand_arr = np.random.random((5,3))
print(rand_arr)
rand_arr=np.round(rand_arr[:4],3)
print(rand_arr)

[[0.57615733 0.59204193 0.57225191]
 [0.22308163 0.95274901 0.44712538]
 [0.84640867 0.69947928 0.29743695]
 [0.81379782 0.39650574 0.8811032 ]
 [0.58127287 0.88173536 0.69253159]]
[[0.576 0.592 0.572]
 [0.223 0.953 0.447]
 [0.846 0.699 0.297]
 [0.814 0.397 0.881]]


19- Pretty print `rand_arr` by suppressing the scientific notation (like 1e10) 
- Input

```Python
# Create the random array
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
```
```Python
rand_arr

#> array([[  5.434049e-04,   2.783694e-04,   4.245176e-04],
#>        [  8.447761e-04,   4.718856e-06,   1.215691e-04],
#>        [  6.707491e-04,   8.258528e-04,   1.367066e-04]])
```

- Desired output:
```python
#> array([[ 0.000543,  0.000278,  0.000425],
#>        [ 0.000845,  0.000005,  0.000122],
#>        [ 0.000671,  0.000826,  0.000137]])
```

In [264]:
# Your code here
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
np.set_printoptions(suppress=True)
rand_arr

array([[0.0005434 , 0.00027837, 0.00042452],
       [0.00084478, 0.00000472, 0.00012157],
       [0.00067075, 0.00082585, 0.00013671]])

20- Limit the number of items printed in python numpy array a to a maximum of 6 elements.
- Input:
```Python
a = np.arange(15)
#> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
```
- Desired output:
```Python
#> array([ 0,  1,  2, ..., 12, 13, 14])
```

In [262]:
# Your code here
a = np.arange(15)
np.set_printoptions(threshold=5)
a

array([ 0,  1,  2, ..., 12, 13, 14])

21- Convert the 1D iris to 2D array iris_2d by omitting the species text field.
- Input:
```Python
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
```
- Desired output:
```Python
#> array([[ 5.1,  3.5,  1.4,  0.2],
#>        [ 4.9,  3. ,  1.4,  0.2],
#>        [ 4.7,  3.2,  1.3,  0.2],
#>        [ 4.6,  3.1,  1.5,  0.2]])
```

In [322]:
# Your code here
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)

# convert each row to a list and get the first 4 items
iris_2d = np.array([row.tolist()[:4] for row in iris_1d])
res=iris_2d[:4]
res

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

22- Find the mean, median, standard deviation of iris's sepallength (1st column)
- Input:
```Python
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
```
- Desired output:
```Python
print(mean, median, sd)
#> 5.84333333333 5.8 0.825301291785
```

In [306]:
# Your code here
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
#here instead of pricising type object we are going to change to flot and take the first row
#usecols is supposed to provide a filter before reading the whole DataFrame into memory;
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

mu, med, sd = np.mean(iris), np.median(iris), np.std(iris)
print(mu, med, sd)
print(iris)

5.843333333333334 5.8 0.8253012917851409
[5.1 4.9 4.7 ... 6.5 6.2 5.9]


23- Create a normalized form of iris‘s sepallength whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.
- Input:
```Python
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
```
- Desired output:
```Python
print(S)
#> [ 0.222  0.167  0.111  0.083  0.194  0.306  0.083  0.194  0.028  0.167
#>   0.306  0.139  0.139  0.     0.417  0.389  0.306  0.222  0.389  0.222
#>   0.306  0.222  0.083  0.222  0.139  0.194  0.194  0.25   0.25   0.111
#>   0.139  0.306  0.25   0.333  0.167  0.194  0.333  0.167  0.028  0.222
#>   0.194  0.056  0.028  0.194  0.222  0.139  0.222  0.083  0.278  0.194
#>   0.75   0.583  0.722  0.333  0.611  0.389  0.556  0.167  0.639  0.25
#>   0.194  0.444  0.472  0.5    0.361  0.667  0.361  0.417  0.528  0.361
#>   0.444  0.5    0.556  0.5    0.583  0.639  0.694  0.667  0.472  0.389
#>   0.333  0.333  0.417  0.472  0.306  0.472  0.667  0.556  0.361  0.333
#>   0.333  0.5    0.417  0.194  0.361  0.389  0.389  0.528  0.222  0.389
#>   0.556  0.417  0.778  0.556  0.611  0.917  0.167  0.833  0.667  0.806
#>   0.611  0.583  0.694  0.389  0.417  0.583  0.611  0.944  0.944  0.472
#>   0.722  0.361  0.944  0.556  0.667  0.806  0.528  0.5    0.583  0.806
#>   0.861  1.     0.583  0.556  0.5    0.944  0.556  0.583  0.472  0.722
#>   0.667  0.722  0.417  0.694  0.667  0.667  0.556  0.611  0.528  0.444]
```

In [325]:
# Your code here
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

# Solution
Iris_max, Iris_min = iris.max(), iris.min()
Iris_normalized = (iris - Iris_min)/(Iris_max - Iris_min)

print(Iris_normalized)

[0.22222222 0.16666667 0.11111111 ... 0.61111111 0.52777778 0.44444444]


24- Find the number and position of missing values in iris_2d‘s sepallength (1st column)
- Input:
```Python
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
```
- Desired output:
```Python
#> Number of missing values: 
...
#> Position of missing values: 
...
```

In [321]:
# Your code here
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
print("Number of missing values: \n", np.isnan(iris_2d[:, 0]).sum())
print("Position of missing values: \n", np.where(np.isnan(iris_2d[:, 0])))

Number of missing values: 
 5
Position of missing values: 
 (array([  2,  53,  99, 100, 111], dtype=int32),)


25- Select the rows of iris_2d that does not have any nan value
- Input:
```Python
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
```

In [344]:
# Your code here
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
for i in iris_2d:
    if np.isnan(i).any()==False:
        print(i)

[5.1 3.5 1.4 0.2]
[4.9 3.  1.4 0.2]
[4.7 3.2 1.3 0.2]
[4.6 3.1 1.5 0.2]
[5.  3.6 1.4 0.2]
[5.4 3.9 1.7 0.4]
[4.6 3.4 1.4 0.3]
[5.  3.4 1.5 0.2]
[4.4 2.9 1.4 0.2]
[4.9 3.1 1.5 0.1]
[5.4 3.7 1.5 0.2]
[4.8 3.4 1.6 0.2]
[4.8 3.  1.4 0.1]
[4.3 3.  1.1 0.1]
[5.8 4.  1.2 0.2]
[5.7 4.4 1.5 0.4]
[5.4 3.9 1.3 0.4]
[5.1 3.5 1.4 0.3]
[5.7 3.8 1.7 0.3]
[5.1 3.8 1.5 0.3]
[5.4 3.4 1.7 0.2]
[5.1 3.7 1.5 0.4]
[4.6 3.6 1.  0.2]
[5.1 3.3 1.7 0.5]
[4.8 3.4 1.9 0.2]
[5.  3.  1.6 0.2]
[5.  3.4 1.6 0.4]
[5.2 3.5 1.5 0.2]
[5.2 3.4 1.4 0.2]
[4.7 3.2 1.6 0.2]
[4.8 3.1 1.6 0.2]
[5.4 3.4 1.5 0.4]
[5.2 4.1 1.5 0.1]
[5.5 4.2 1.4 0.2]
[4.9 3.1 1.5 0.1]
[5.  3.2 1.2 0.2]
[5.5 3.5 1.3 0.2]
[4.9 3.1 1.5 0.1]
[4.4 3.  1.3 0.2]
[5.1 3.4 1.5 0.2]
[5.  3.5 1.3 0.3]
[4.5 2.3 1.3 0.3]
[4.4 3.2 1.3 0.2]
[5.  3.5 1.6 0.6]
[5.1 3.8 1.9 0.4]
[4.8 3.  1.4 0.3]
[5.1 3.8 1.6 0.2]
[4.6 3.2 1.4 0.2]
[5.3 3.7 1.5 0.2]
[5.  3.3 1.4 0.2]
[7.  3.2 4.7 1.4]
[6.4 3.2 4.5 1.5]
[6.9 3.1 4.9 1.5]
[5.5 2.3 4.  1.3]
[6.5 2.8 4.6 1.5]
[5.7 2.8 4

26- Replace all ccurrences of `nan` with 0 in numpy array
- Input
```Python
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
```

In [343]:
# Your code here
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
print(iris_2d[:4])
iris_2d[np.isnan(iris_2d)] = 0
print(iris_2d[:4])

[[5.1 3.5 nan 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]]
[[5.1 3.5 0.  0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]]


27- Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> 'small'
- 3-5 –> 'medium'
- '>=5 –> 'large'
- Input 
```Python
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
```
- Desired output:
```Python
petal_length_cat[:4]
#> ['small', 'small', 'small', 'small']
```

In [346]:
# Your code here
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

petal_length_bin = np.digitize(iris[:, 2].astype('float'), [0, 3, 5, 10])


label_map = {1: 'small', 2: 'medium', 3: 'large', 4: np.nan}
petal_length_cat = [label_map[x] for x in petal_length_bin]

petal_length_cat[:4]


['small', 'small', 'small', 'small']

28- Find the position of the first occurrence of a value greater than 1.0 in petalwidth 4th column of iris dataset.
- Input 
```Python
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
```
- Desired output:
```Python
#> 50
```

In [347]:
# Your code here
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

np.argwhere(iris[:, 3].astype(float) > 1.0)[0]

array([50], dtype=int32)

29- From the array a, replace all values greater than 30 to 30 and less than 10 to 10. 
- Input:
```Python
np.random.seed(100)
a = np.random.uniform(1,50, 20)
```
- Desired output:
```Python
#> [ 27.63  14.64  21.8   30.    10.    10.    30.    30.    10.    29.18  30.
#>   11.25  10.08  10.    11.77  30.    30.    10.    30.    14.43]
```

In [356]:
# Your code here
np.random.seed(100)
a = np.random.uniform(1,50, 20)
print(a)
mask1 = (a >= 30)
a[mask1]=30
print(a)
mask2=(a<=10)
a[mask2]=10
print(a)

[27.62684215 14.64009987 21.80136195 ...  9.42510962 40.99501269
 14.42961361]
[27.62684215 14.64009987 21.80136195 ...  9.42510962 30.
 14.42961361]
[27.62684215 14.64009987 21.80136195 ... 10.         30.
 14.42961361]


30- Import the image from the following URL and convert it to a numpy array. URL = ‘https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg’
- Input
```Python
from io import BytesIO
from PIL import Image
import PIL, requests
```

In [13]:
# Your code here
from io import BytesIO
from PIL import Image
import PIL, requests
url ="https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg"
response = requests.get(url)
img = Image.open(BytesIO(response.content))
print(img.size)
img_array = np.asarray(img)
img_array.shape

(452, 303)


(303, 452, 3)